version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: di_mebel_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: di_mebel_db
      MYSQL_USER: admin_di_mebel
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: di_mebel_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: di_mebel_db
      DB_USER: admin_di_mebel
      DB_PASS: admin
    volumes:
      - .:/app

volumes:
  db_data:
