version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: di_mebel_mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: di_mebel_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env
    environment:
      DB_HOST: db  # Переопределяем DB_HOST для внутренней сети Docker
    volumes:
      - .:/app

volumes:
  db_data:
