services:
  di_mebel_db:
    image: mysql:8.0
    container_name: di_mebel_mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${SECRET_KEY}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5



  app:
    build: .
    container_name: di_mebel_app
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - di_mebel_db
    environment:
      DB_HOST: di_mebel_db


