# Generated by Django 5.1.6 on 2025-02-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_image_category_image_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
