# Generated by Django 5.1.6 on 2025-03-04 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0003_delete_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='furniture_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furniture.furniture'),
        ),
    ]
