# Generated by Django 5.1.6 on 2025-03-15 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_image_furniture_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='furniture_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='furniture.furniture'),
        ),
        migrations.CreateModel(
            name='FurnitureColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.color')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furniture.furniture')),
            ],
        ),
        migrations.AddField(
            model_name='color',
            name='furnitures',
            field=models.ManyToManyField(related_name='colors', through='furniture.FurnitureColor', to='furniture.furniture'),
        ),
    ]
