# Generated by Django 5.1.6 on 2025-03-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0004_image_furniture_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='colors/')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='furniture_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='furniture.furniture'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='furnitures', to='furniture.color'),
        ),
    ]
