# Generated by Django 5.1.6 on 2025-03-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0005_color_alter_image_furniture_id_furniturecolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
